### ISSUE TITLE
./configure won't run

### ISSUE THREAD

**Issue by ghenry** [sipwise/sipsak#4]
Hi,

Is this supposed to build?

./configure: 1656: ./configure.lineno: configure:: : not found
./configure: 1664: ./configure.lineno: configure:: $? = 0: not found
./configure: 1671: ./configure.lineno: configure: failed program was:: not found
sed: can't read conftest.: No such file or directory
./configure: 1681: ./configure.lineno: /bin/arch: not found
/usr/bin/arch: invalid option -- 'k'
Try '/usr/bin/arch --help' for more information.
./configure: 1683: ./configure.lineno: /usr/convex/getsysinfo: not found
./configure: 1684: ./configure.lineno: /usr/bin/hostinfo: not found
./configure: 1685: ./configure.lineno: /bin/machine: not found
./configure: 1686: ./configure.lineno: /usr/bin/oslevel: not found
./configure: 1687: ./configure.lineno: /bin/universe: not found
./configure: 1690: ./configure.lineno: Syntax error: "fi" unexpected

Is this the official git repo?

Thanks.

**Comment by taurus-forever** [comment]
> Is this supposed to build?

Yes, it builds properly in our Debian Jessie environment.

> Is this the official git repo?

Official sipsak repo is here https://github.com/nils-ohlmeier/sipsak

**Comment by ghenry** [comment]
Thanks. Well, it doesn't. Official repo does. Thanks for the link!

**Comment by mika** [comment]
JFTR: the autoconf files (derived from original upstream) are very old and outdated, that's why our Debian package build executes `autoreconf -f -i` (behind the scenes via `dh_autoreconf`, see `debian/rules`).

So if you want to build it manually just invoke `autoreconf -f -i` and the rest should work just fine.
HTH

**Comment by guillemj** [comment]
@mika Right, that's one of the reasons why storing such autogenerated files in a VCS is usually a bad idea. Of course that conflicts with wanting to store the exact same contents as shipped in a Debian source package. :) Maybe we should just remove those to avoid confusing people?

**Comment by mika** [comment]
@guillemj yeah, it's just coming from the upstream import (see https://github.com/nils-ohlmeier/sipsak), I've no objections to clean this up as long as we can still easily sync with upstream (if that should be relevant anytime in the future) :)

**Comment by ghenry** [comment]
I did do autoreconf -iv, but that failed. I'll check -f

On 19 May 2016 at 14:06, Michael Prokop <notifications@github.com> wrote:

> JFTR: the autoconf files (derived from original upstream) are very old and
> outdated, that's why our Debian package build executes autoreconf -f -i
> (behind the scenes via dh_autoreconf, see debian/rules).
>
> So if you want to build it manually just invoke autoreconf -f -i and the
> rest should work just fine.
> HTH
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sipwise/sipsak/issues/4#issuecomment-220318280>
>



-- 
Kind Regards,

Gavin Henry.

**Comment by davemc50** [comment]
`autoreconf -f -i`

fixes it...

`root@box:/opt/sipsak# ./configure
./configure: 1656: ./configure.lineno: configure:: : not found
./configure: 1664: ./configure.lineno: configure:: $? = 0: not found
./configure: 1671: ./configure.lineno: configure: failed program was:: not found
sed: can't read conftest.: No such file or directory
./configure: 1681: ./configure.lineno: /bin/arch: not found
/usr/bin/arch: invalid option -- 'k'
Try '/usr/bin/arch --help' for more information.
./configure: 1683: ./configure.lineno: /usr/convex/getsysinfo: not found
./configure: 1684: ./configure.lineno: /usr/bin/hostinfo: not found
./configure: 1685: ./configure.lineno: /bin/machine: not found
./configure: 1686: ./configure.lineno: /usr/bin/oslevel: not found
./configure: 1687: ./configure.lineno: /bin/universe: not found
./configure: 1690: ./configure.lineno: Syntax error: "fi" unexpected`

`root@box:/opt/sipsak# autoreconf -f -i
tests/Makefile.am:5: warning: source file '$(top_builddir)/helper.c' is in a subdirectory,
tests/Makefile.am:5: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
tests/Makefile.am:5: warning: source file '$(top_builddir)/exit_code.c' is in a subdirectory,
tests/Makefile.am:5: but option 'subdir-objects' is disabled
parallel-tests: installing './test-driver'`

`root@box:/opt/sipsak# ./configure          
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
....
`

**Comment by guillemj** [comment]
Hi!

I got all this fixed and merged upstream (https://github.com/nils-ohlmeier/sipsak), plus sent all local deltas to upstream too. So there should really be no need to use this fork now anymore.

Please use Nils repo. And we should probably just get rid of this repo, as it will just cause confusion.
