### ISSUE TITLE
defunct list

### ISSUE THREAD

**Issue by THUFIR** [sipwise/sipsak#6]
subscribe messages to the user list bounce.

**Comment by guillemj** [comment]
I've cherry picked this from upstream, fixed now, thanks!

**Comment by THUFIR** [comment]
pardon, still bounces for me:

Delivery to the following recipient failed permanently:

     sipsak@lists.sipsak.org

Technical details of permanent failure:
DNS Error: 113013016 DNS type 'mx' lookup of lists.sipsak.org responded with code NXDOMAIN
Domain name not found: lists.sipsak.org

**Comment by nils-ohlmeier** [comment]
I took the website and the email list offline quite some time ago. I currently have no plans to restart them. The original code is now hosted here: https://github.com/nils-ohlmeier/sipsak
